-- this is a comment in sql, most editors will apply comment syntax if you use Ctrl+/
-- quick tour: create a dogs table, add dogs to it, modify those records, delte some, clean up the table
-- SQL is not case sensitive
begin; -- starting a manually controlled transaction, nothing will be permanently saved to the DB until a COMMIT
create table dogs (
	id serial, --most tables will have a unique id column which is helpful for normalization, SERIAL is autoincrementing INT in postgres
	name text not null, --name is required
	color text check(color in ('brown', 'black', 'white', 'tan', 'red')), --text is fine to represent text.  check allows us to constrain values
	num_legs int default(4) --int for integer, providing a default value
);

--write an insert specifying all columns,use DEFAULT for autogenerated values:
insert into dogs values 
	(default, 'fido', 'brown', default),
	(default, 'rex', 'black', default),
	(default, 'kibo', 'brown', 3);
--write an insert only specifying some columns.  Non-specified non-generated columns will be NULL
--inserting dogs that fail our check constraint doesn't work
--insert into dogs(name, color) values ('fido 2','blue'), ('fido 3','green'), ('clifford','red'), ('fido 5','yellow');
insert into dogs(name, color) values ('clifford', 'red');

--update modifies individual records
update dogs set color='tan' where id=4;

--delete removes records.  Deleting without having a where clause is almost always a bad idea (will delete all records)
delete from dogs where color='brown';

--truncate dogs; --remove all records from the table

select * from dogs;

rollback; -- rollback ends a transaction by undoing it.  It's possible to rollback to a savepoint instead.